/**
 * כל בני המשפחה נמצאים בקובץ הזה בלבד.
 * כדי להוסיף אדם: מעתיקים שורה, משנים שם ותאריך ושומרים.
 * month הוא מספר החודש (1–12), day הוא היום בחודש.
 * memorial: true מציג ז״ל במקום גיל.
 */
export const familyMembers = [
  { name: "שירה עזרא", day: 5, month: 1, year: 1981, icon: "🎂" },
  { name: "נחום אברהם", day: 8, month: 1, year: 1982, icon: "🎂" },
  { name: "טליה היימס עזרא", day: 11, month: 1, year: 2004, icon: "🎂" },
  { name: "ג׳ון", day: 16, month: 1, year: 1975, icon: "🎂" },
  { name: "עלמה כהן", day: 18, month: 1, year: 2021, icon: "🎀" },
  { name: "ג׳דה בן אל", day: 20, month: 1, year: 1954, icon: "🎁" },
  { name: "מרום יעקובי", day: 14, month: 2, year: 2025, icon: "🎈" },
  { name: "רוית אברהם", day: 19, month: 2, year: 1983, icon: "🎂" },
  { name: "זהבה מלול", day: 1, month: 3, year: 1955, icon: "🎁" },
  { name: "שלי לרון אברהם", day: 11, month: 3, year: 1980, icon: "🎂" },
  { name: "דין מייקל בן יהודה", day: 12, month: 3, year: 2021, icon: "🎈" },
  { name: "עמנואל ארי כהן", day: 19, month: 3, year: 2017, icon: "🎈" },
  { name: "ציון עזרא", day: 24, month: 3, year: 1956, icon: "🎁" },
  { name: "דריה אדיבי", day: 26, month: 3, year: 2014, icon: "🎀" },
  { name: "שחר עזרא", day: 27, month: 3, year: 2017, icon: "🎈" },
  { name: "נעמה אדיבי", day: 1, month: 4, year: 2020, icon: "🎀" },
  { name: "אור-לי אלופי", day: 9, month: 4, year: 1986, icon: "🎂" },
  { name: "יניב יעקובי", day: 12, month: 4, year: 1972, icon: "🎂" },
  { name: "גלי אדיבי", day: 20, month: 4, year: 1983, icon: "🎂" },
  { name: "פיני אדיבי", day: 26, month: 4, year: 1981, icon: "🎂" },
  { name: "אדם אברהם שלו", day: 29, month: 4, year: 2025, icon: "🎈" },
  { name: "זיו מלול", day: 2, month: 5, year: 2023, icon: "🎈" },
  { name: "מיכל בן יהודה", day: 9, month: 5, year: 1989, icon: "🎂" },
  { name: "יוסי אברהם", day: 14, month: 5, year: 1948, icon: "🕯️", memorial: true },
  { name: "איתמר בן יהודה", day: 20, month: 5, year: 1960, icon: "🎁" },
  { name: "יעלי עזרא", day: 24, month: 5, year: 1962, icon: "🎁" },
  { name: "אביתר אברהם", day: 1, month: 6, year: 2012, icon: "🎮" },
  { name: "אהוד בן יהודה", day: 3, month: 6, year: 1983, icon: "🎂" },
  { name: "ולנטינה בן יהודה", day: 8, month: 6, year: 1985, icon: "🎂" },
  { name: "טירן היימס עזרא", day: 16, month: 6, year: 1967, icon: "🎂" },
  { name: "הילה יעקובי", day: 17, month: 6, year: 1977, icon: "🎂" },
  { name: "נוגה מלול", day: 22, month: 6, year: 2020, icon: "🎀" },
  { name: "יפה אברהם", day: 24, month: 6, year: 1952, icon: "🕯️", memorial: true },
  { name: "נאיה בן יהודה", day: 6, month: 7, year: 2022, icon: "🎀" },
  { name: "חיים היימס עזרא", day: 8, month: 7, year: 1966, icon: "🎁" },
  { name: "עמית עזרא", day: 10, month: 7, year: 1984, icon: "🎂" },
  { name: "אלה עזרא", day: 14, month: 7, year: 2010, icon: "🎵" },
  { name: "אביגיל אברהם", day: 14, month: 7, year: 2014, icon: "🎀" },
  { name: "יובל עזרא", day: 28, month: 7, year: 2013, icon: "🎮" },
  { name: "יערה היימס עזרא", day: 1, month: 8, year: 2001, icon: "🎂" },
  { name: "שירלי אברהם", day: 3, month: 8, year: 1983, icon: "🎂" },
  { name: "עתי עזרא", day: 12, month: 8, year: 2016, icon: "🎈" },
  { name: "עמית פרנקל", day: 26, month: 8, year: 2011, icon: "🎮" },
  { name: "מגל מלול", day: 27, month: 8, year: 1990, icon: "🎂" },
  { name: "אוריה אברהם", day: 30, month: 8, year: 2009, icon: "🎮" },
  { name: "זוהר בן יהודה", day: 3, month: 9, year: 1985, icon: "🎂" },
  { name: "הראל כהן", day: 6, month: 9, year: 2018, icon: "🎈" },
  { name: "קורן מלול", day: 13, month: 9, year: 2024, icon: "🎈" },
  { name: "תום אוריה כהן", day: 21, month: 9, year: 1989, icon: "🎂" },
  { name: "אביעד כהן", day: 26, month: 9, year: 1985, icon: "🎂" },
  { name: "אבירם אברהם", day: 3, month: 10, year: 1980, icon: "🎂" },
  { name: "רנן אלבי יעקובי", day: 6, month: 10, year: 2020, icon: "🎈" },
  { name: "דרור מלול", day: 16, month: 10, year: 1991, icon: "🎂" },
  { name: "נורית עזרא", day: 20, month: 10, year: 1936, icon: "🕯️", memorial: true },
  { name: "אגם עזרא", day: 23, month: 10, year: 2011, icon: "🎵" },
  { name: "עומרי אברהם", day: 29, month: 10, year: 1986, icon: "🎂" },
  { name: "גידי ספרינצין", day: 7, month: 11, year: 1980, icon: "🎂" },
  { name: "ליאור אברהם", day: 11, month: 11, year: 2021, icon: "🎈" },
  { name: "נוריה בן אל", day: 11, month: 11, year: 1982, icon: "🎂" },
  { name: "רומי עזרא", day: 18, month: 11, year: 2013, icon: "🎀" },
  { name: "אייל עזרא", day: 20, month: 11, year: 1981, icon: "🎂" },
  { name: "נועם בן יהודה", day: 28, month: 11, year: 2017, icon: "🎈" },
  { name: "רותם מלול", day: 29, month: 11, year: 1987, icon: "🎂" },
  { name: "אוריה בן יהודה", day: 30, month: 11, year: 1986, icon: "🎂" },
  { name: "ליה אברהם", day: 6, month: 12, year: 2019, icon: "🎀" },
  { name: "בועז פרנקל", day: 17, month: 12, year: 2018, icon: "🎈" },
  { name: "גאיה נוריה בן יהודה", day: 19, month: 12, year: 2024, icon: "🎀" },
  { name: "שמחה בן יהודה", day: 20, month: 12, year: 1958, icon: "🕯️", memorial: true },
  { name: "שרית גביש עזרא", day: 21, month: 12, year: 1978, icon: "🎂" },
  { name: "אלון אדיבי", day: 25, month: 12, year: 2010, icon: "🎮" },
];
